### ISSUE TITLE
poll results are not accessible by user 1 if she has not voted

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/poll#14]
User 1 has to have voted to a poll to see the results, and otherwise she gets a 403 message.

**Comment by alanmels** [comment]
Couldn't replicate the issue on a fresh Backdrop setup with user #2 having already voted and admin accessing the results without any error:

![Screenshot 2022-11-07 at 3 33 29 PM](https://user-images.githubusercontent.com/56604405/200420320-771aea17-089a-4e62-928a-ea0ef4b2920c.png)
![Screenshot 2022-11-07 at 3 33 36 PM](https://user-images.githubusercontent.com/56604405/200420342-ca0dccfe-76fd-4a4f-9d02-a4047c86e761.png)

**Comment by alanmels** [comment]
After thorough testing I was able to replicate the issue. In particular, I disabled, uninstalled and then re-installed the module, and because database contained old poll nodes, but did not contain poll data, the poll results became inaccessible including for user 1.

The initial module port was done quite row on "as is" principle, therefore it didn't have implementation of important hooks to properly uninstall the module without leaving traces in the database. The issue should be fixed by https://github.com/backdrop-contrib/poll/commit/58de5e3b4da0afe582ee2af95c43f6b3eb2da301 Please give it a try and let me know if the problem still persists for you.

**Comment by robertgarrigos** [comment]
Thanks @alanmels I confirm that this fixed the problem

**Comment by robertgarrigos** [comment]
But watch out that there is a dpm() function on hook_uninstall() function

**Comment by alanmels** [comment]
Nice catch, thanks.
